### ISSUE TITLE
[BUG] Vanilla prefixes, suffixes and colors seems not to work

### ISSUE THREAD

**Issue by vipaoL** [jewlexx/TabLocation#3]
**Describe the bug**
The plugin breaks vanilla features of the "/team" command: prefixes, colors and suffixes.

**To Reproduce**
`/team add test`
`/team modify test color aqua`
`/team modify test prefix "prefix"`
`/team modify test suffix "suffix"`
`/team join test @s`

**Screenshots**
without the plugin:
![screenshot](https://user-images.githubusercontent.com/59665125/205902201-81f84e76-4365-4b0c-930b-dd09156cb193.png)

with:
![screenshot](https://user-images.githubusercontent.com/59665125/205901966-c288738b-edb1-425c-a272-be58378f8586.png)

**Server:**
 - OS: [Linux]
- Java: [OpenJDK 17.0.3 2022-04-19]
- Minecraft: [1.19.2]
- Plugin: [1.5.0]

**Additional context**
[Some info about /team command](https://minecraft.fandom.com/wiki/Commands/team)

**Comment by jewlexx** [comment]
Hey, apologies for the very late response, I honestly haven't checked this plugin in about a year.
I'll work on patching this in the [next](https://github.com/jewlexx/TabLocation/pull/7) version.
